  
---

apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
  labels:
    name: homeassistant
    
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
        - name: ha-storage
          persistentVolumeClaim:
            claimName: homeassistant-storage
        - name: dev-usb1
          hostPath:
            path: /dev/ttyUSB1
      containers:
        - name: raspberrypi4-homeassistant
          image: 'homeassistant/home-assistant'
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - name: ha-storage
              mountPath: /config
            - mountPath: /dev/ttyUSB1
              name: dev-usb1
          securityContext:
            privileged: true
      restartPolicy: Always
      hostNetwork: true
      nodeSelector:
        homeassistant: supported
