---

kind: Service
apiVersion: v1
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
    kubernetes.io/name: homeassistant
spec:
  ports:
    - name: homeassistant
      protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 30438
  selector:
    app: homeassistant
  type: NodePort
  sessionAffinity: None
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: "ha-ingress"
  namespace: homeassistant

spec:
  rules:
    - host: my-ha.net
      http:
        paths:
          - path: /
            backend:
              serviceName: homeassistant
              servicePort: 8123
