---

kind: Service
apiVersion: v1
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
    kubernetes.io/name: homeassistant
spec:
  ports:
    - name: homeassistant
      protocol: TCP
      port: 80
      targetPort: 8123
      nodePort: 30438
  selector:
    app: homeassistant
  type: NodePort
  sessionAffinity: None
---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: my-ha.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 80
